# DLT Manager — ABN environment values

component: backend
stage: abn
replicas: 1
revisionHistoryLimit: 0

image:
  repository: dev.docker.system.local/elpa-dltmanager-tst/dltmanager
  tag: ""

frontendImage:
  repository: dev.docker.system.local/elpa-dltmanager-tst/dltmanager-ui
  tag: ""

jwt:
  url: https://employee.login.abn.signal-iduna.org/
  authorizedUsers: S000325

postgres:
  host: vipsiae11a.system.local
  port: "5432"
  database: elpapga
  schema: dlt_manager
  user: elpa_dltmanager_abn
  sslMode: prefer
  flywayEnabled: "true"

kafka:
  bootstrapServers: bootstrap-nop.kafka.svc.cluster.local:9093
  oauthTokenEndpoint: https://employee.login.abn.signal-iduna.org/protocol/openid-connect/token
  securityProtocol: SASL_PLAINTEXT

secrets:
  name: elpa-secrets

logLevel: INFO
logLevelSi: DEBUG

resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 400m
    memory: 950Mi

frontendResources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

frontend:
  backendUrl: https://abn-dltmanager-elpa-elpa4.copsinop.de
