apiVersion: v1
kind: Service
metadata:
  name: {{ include "copsi.name" . }}
  labels:
    {{- include "copsi.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "copsi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      appProtocol: http
{{- if eq .Values.component "backend" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "copsi.name" . }}-metrics
  labels:
    {{- include "copsi.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "copsi.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      appProtocol: http
{{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "copsi.name" . }}
  labels:
    {{- include "copsi.labels" . | nindent 4 }}
spec:
  hosts:
    - "{{ include "copsi.name" . }}-elpa-elpa4.copsinop.de"
    - "{{ include "copsi.name" . }}.elpa-elpa4.svc.cluster.local"
  gateways:
    - istio-system/mesh-gateway
    - mesh
  http:
    - route:
        - destination:
            host: {{ include "copsi.name" . }}
            port:
              number: 8080
{{- if eq .Values.component "backend" }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "copsi.name" . }}-metrics
  labels:
    {{- include "copsi.labels" . | nindent 4 }}
spec:
  hosts:
    - "{{ include "copsi.name" . }}-metrics-elpa-elpa4.copsinop.de"
    - "{{ include "copsi.name" . }}-metrics.elpa-elpa4.svc.cluster.local"
  gateways:
    - istio-system/mesh-gateway
    - mesh
  http:
    - route:
        - destination:
            host: {{ include "copsi.name" . }}-metrics
            port:
              number: 8081
{{- end }}
