apiVersion: v1
kind: Template
metadata:
  name: ${RESOURCE_NAME}-template

parameters:
  - description: The full name and tag of the image to be used for the deployment.
    displayName: Full docker image name.
    name: IMAGE_NAME
    required: true

  - description: Name of origin branch
    displayName: Branch name
    name: BRANCH_NAME
    required: true

  - description: Commit ID of HEAD
    displayName: Commit ID
    name: COMMIT_ID
    required: true

  - description: Unique Name of openshift resource.
    displayName: Name of openshift resource.
    name: RESOURCE_NAME
    required: true

  - description: The cluster url including the project subdomain.
    displayName: Project url.
    name: PROJECT_URL
    required: true

  - description: Name of stage property config map
    displayName: Config map name
    name: STAGE_PROPERTY_MAP
    required: true

  - description: Target segment (tst]abn]prd)
    displayName: Target segment (tst]abn]prd)
    name: TARGET_SEGMENT
    required: true

  - description: The route base url, including the project base url, e.g. "develop-backend-sdasi-blueprint-tst.osot.system.local"
    displayName: Base route url.
    name: BASE_ROUTE_URL
    required: true

  - description: Number of replicas / pods to run at all times (affects quotas!)
    displayName: Number of replicas
    name: NUM_REPLICAS
    required: true

  - description: Minimum/guaranteed amount of CPU cores required for scheduling (affects quotas!)
    displayName: Guaranteed amount of CPU cores
    name: REQUESTS_CPU
    required: true

  - description: Minimum/guaranteed amount of memory required for scheduling (affects quotas!)
    displayName: Guaranteed amount of memory
    name: REQUESTS_MEMORY
    required: true

  - description: Maximum amount of CPU core usage allowed per pod (best effort and capped)
    displayName: Maximum amount of CPU usage
    name: LIMITS_CPU
    required: true

  - description: Maximum amount of memory usage allowed per pod (OOM kill)
    displayName: Maximum amount of memory usage
    name: LIMITS_MEMORY
    required: true

  - description: Password for technical user for authentification
    displayName: technical user password
    name: AUTH_PASSWORD
    required: true

  - description: Name of secret file
    displayName: Name of secret file
    name: SECRET_FILE_NAME
    required: true

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${RESOURCE_NAME}
      labels:
        app: ${BRANCH_NAME}
        branch: ${BRANCH_NAME}
        commit-id: ${COMMIT_ID}
    spec:
      replicas: ${{NUM_REPLICAS}}
      selector:
        config: ${RESOURCE_NAME}
        branch: ${BRANCH_NAME}
      template:
        metadata:
          labels:
            config: ${RESOURCE_NAME}
            branch: ${BRANCH_NAME}
            sdasi/metrics: 'true'
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: config
                          operator: In
                          values:
                            - ${RESOURCE_NAME}
                    topologyKey: datacenter
                  weight: 100
          containers:
            - name: ${RESOURCE_NAME}
              image: ${IMAGE_NAME}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8081
                  protocol: TCP
              resources:
                limits:
                  cpu: '${LIMITS_CPU}'
                  memory: '${LIMITS_MEMORY}'
                requests:
                  cpu: '${REQUESTS_CPU}'
                  memory: '${REQUESTS_MEMORY}'
              envFrom:
                - configMapRef:
                    name: ${STAGE_PROPERTY_MAP}
              env:
                - name: JDK_JAVA_OPTIONS
                  value: '-XX:+UseSerialGC -XX:MaxRAMPercentage=50 -XX:InitialRAMPercentage=25 -XX:+UseStringDeduplication'
                - name: KAFKA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: elpa-dltmanager-${TARGET_SEGMENT}
                - name: AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: AUTH_PASSWORD
                      name: ${SECRET_FILE_NAME}
                - name: MONGODB_OPTIONS
                  valueFrom:
                    configMapKeyRef:
                      name: ${BRANCH_NAME}-mongodb
                      key: MONGODB_OPTIONS
                - name: MONGODB_HOSTS
                  valueFrom:
                    configMapKeyRef:
                      name: ${BRANCH_NAME}-mongodb
                      key: MONGODB_HOSTS
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${BRANCH_NAME}-mongodb
                      key: MONGODB_USER
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${BRANCH_NAME}-mongodb
                      key: MONGODB_PASSWORD
              readinessProbe:
                httpGet:
                  path: /health/readiness
                  port: 8081
                periodSeconds: 20
                timeoutSeconds: 5
              livenessProbe:
                httpGet:
                  path: /health/liveness
                  port: 8081
                failureThreshold: 5
                periodSeconds: 15
              startupProbe:
                httpGet:
                  path: /health/readiness
                  port: 8081
                failureThreshold: 9
                periodSeconds: 10
                timeoutSeconds: 5
          securityContext:
            supplementalGroups: [5555]
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${RESOURCE_NAME}
      labels:
        branch: ${BRANCH_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: admin-port
          port: 8081
          protocol: TCP
          targetPort: 8081
      selector:
        config: ${RESOURCE_NAME}
        branch: ${BRANCH_NAME}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${RESOURCE_NAME}-tls
      annotations:
        haproxy.router.openshift.io/disable_cookies: "True"
      labels:
        branch: ${BRANCH_NAME}
    spec:
      host: "${BASE_ROUTE_URL}"
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: "${RESOURCE_NAME}"
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${RESOURCE_NAME}-admin-tls
      annotations:
        haproxy.router.openshift.io/disable_cookies: "True"
      labels:
        branch: ${BRANCH_NAME}
    spec:
      host: "adm-${BASE_ROUTE_URL}"
      port:
        targetPort: 8081
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: "${RESOURCE_NAME}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_FILE_NAME}
    stringData:
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
