apiVersion: v1
kind: Template
metadata:
  name: ${RESOURCE_NAME}-template

parameters:
  - description: The full name and tag of the image to be used for the deployment.
    displayName: Full docker image name.
    name: IMAGE_NAME
    required: true

  - description: Name of origin branch
    displayName: Branch name
    name: BRANCH_NAME
    required: true

  - description: Commit ID of HEAD
    displayName: Commit ID
    name: COMMIT_ID
    required: true

  - description: Unique Name of openshift resource.
    displayName: Name of openshift resource.
    name: RESOURCE_NAME
    required: true

  - description: The cluster url including the project subdomain.
    displayName: Project url.
    name: PROJECT_URL
    required: true

  - description: Name of stage property config map
    displayName: Config map name
    name: STAGE_PROPERTY_MAP
    required: true

  - description: Number of replicas / pods to run at all times (affects quotas!)
    displayName: Number of replicas
    name: NUM_REPLICAS
    required: true

  - description: Minimum/guaranteed amount of CPU cores required for scheduling (affects quotas!)
    displayName: Guaranteed amount of CPU cores
    name: REQUESTS_CPU
    required: true

  - description: Minimum/guaranteed amount of memory required for scheduling (affects quotas!)
    displayName: Guaranteed amount of memory
    name: REQUESTS_MEMORY
    required: true

  - description: Maximum amount of CPU core usage allowed per pod (best effort and capped)
    displayName: Maximum amount of CPU usage
    name: LIMITS_CPU
    required: true

  - description: Maximum amount of memory usage allowed per pod (OOM kill)
    displayName: Maximum amount of memory usage
    name: LIMITS_MEMORY
    required: true

  - description: Backend URL
    displayName: Application backend url
    name: BACKEND_URL
    required: true

  - description: The route base url, including the project base url
    displayName: Base route url.
    name: BASE_ROUTE_URL
    required: true

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${RESOURCE_NAME}
      labels:
        app: ${BRANCH_NAME}
        branch: ${BRANCH_NAME}
        commit-id: ${COMMIT_ID}
    spec:
      replicas: ${{NUM_REPLICAS}}
      selector:
        config: ${RESOURCE_NAME}
        branch: ${BRANCH_NAME}
      template:
        metadata:
          labels:
            config: ${RESOURCE_NAME}
            branch: ${BRANCH_NAME}
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: name
                          operator: In
                          values:
                            - ${RESOURCE_NAME}
                    topologyKey: datacenter
                  weight: 100
          containers:
            - name: ${RESOURCE_NAME}
              image: ${IMAGE_NAME}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: '${LIMITS_CPU}'
                  memory: '${LIMITS_MEMORY}'
                requests:
                  cpu: '${REQUESTS_CPU}'
                  memory: '${REQUESTS_MEMORY}'
              env:
                - name: BACKEND_URL
                  value: ${BACKEND_URL}
              envFrom:
                - configMapRef:
                    name: ${STAGE_PROPERTY_MAP}
              lifecycle:
                preStop:
                  exec:
                    command: [ "/usr/sbin/nginx","-s","quit" ]
          terminationGracePeriodSeconds: 600
          securityContext:
            supplementalGroups: [ 5555 ]
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${RESOURCE_NAME}
      labels:
        branch: ${BRANCH_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        config: ${RESOURCE_NAME}
        branch: ${BRANCH_NAME}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${RESOURCE_NAME}-tls
      labels:
        branch: ${BRANCH_NAME}
    spec:
      host: "${BASE_ROUTE_URL}"
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: "${RESOURCE_NAME}"